sudo: required
services:
        - docker

before_install:
        - docker build -t sidagalidocker/my-rust-app-dev -f Dockerfile.dev .

script:
        - docker run sidagalidocker/my-rust-app-dev

deploy:
        on:
                branch: master
