version: '3'
services:
        alpine-rust-app:
                build: .
                entrypoint: ["tail", "-f", "/dev/null"]
                environment:
                        - redis_server=redis_server_docker
        redis-server:
                image: 'redis:alpine'
                hostname: redis_server_docker
                volumes:
                        - ./redis_data:/data
                        - ./redis_conf:/usr/local/etc/redis/
                command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
