version: '3'
services:
        alpine-rust-app:
                build: .
                entrypoint: ["tail", "-f", "/dev/null"]
                environment:
                        - redis_server=redis_server_docker
        redis-server:
                image: 'redis:alpine'
                hostname: redis_server_docker
