FROM rust:alpine as builder
LABEL stage=builder

WORKDIR /my_rust_app
COPY . /my_rust_app

RUN apk add --update gcc musl-dev

RUN apk add --update redis

COPY ./start_dev.sh .

# run app
CMD ["sh", "start_dev.sh"]
